### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by goyalsaransh97** [huggingface/pytorch-transformers#546]
I'm getting error " ImportError: cannot import name 'WEIGHTS_NAME' from 'pytorch_pretrained_bert.file_utils' " on running run_squad.py. I've already tried building from source but the problem persists.

**Comment by thomwolf** [comment]
This should be fixed with the new release (0.6.2).

**Comment by Barthold-Albrecht** [comment]
Unfortunately, I still get this error with the new release. Could that be because I had installed the package before some time ago (and removed it afterwards)?
